default:
  image: node:latest

  before_script:
    - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest

stages:
  - build
  - test
  - deploy

build:android:
  stage: build
  script:
    - npm run build-android

build:ios:
  stage: build
  script:
    - npm run build-ios

test:
  stage: test
  script:
    - npm run test

deploy:expo:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo publish --non-interactive
