default:
  image: node:latest

  before_script:
    - npm install --legacy-peer-deps
    - npm install -g expo-cli 

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - node_modules/
    - .jest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm run test

deploy:expo:
  stage: deploy
  script:
    - expo publish --non-interactive
  only:
    - master
